# Generated by Django 2.2.4 on 2019-09-01 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('date_taken', models.DateField(default=django.utils.timezone.now)),
                ('friends_name', models.CharField(max_length=150)),
                ('image_file', models.ImageField(null=True, upload_to='')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
